# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - restaurant-ruczaj-server

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_b06c07ddef0f470b8b316fe5143dee09 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_6ffee50333834cc496ab003c62fd834c }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_b06c07ddef0f470b8b316fe5143dee09 }}/restaurant-ruczaj-server:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'restaurant-ruczaj-server'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_bee1be63d3ce424cb92b7d8012075a3e }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_b06c07ddef0f470b8b316fe5143dee09 }}/restaurant-ruczaj-server:${{ github.sha }}'